- name: Send Discord Message
  uri:
    url: "{{ discord_webhook }}"
    method: 'POST'
    body_format: json
    body: {
      'content': "{{ discord_message }}",
      'username': "{{ discord_name }}",
      'avatar_url': "{{ discord_avatar }}"
    }
    status_code: 204