- name: Send Discord Message - Basic
  uri:
    url: "{{ discord_webhook }}"
    method: 'POST'
    body_format: json
    body: {
      'content': "{{ discord_message }}",
      'username': "{{ discord_name }}",
      'avatar_url': "{{ discord_avatar }}"
    }
    status_code: 204
  when:
    - discord_type == 'basic'

- name: Send Discord Message - Embed
  uri:
    url: "{{ discord_webhook }}"
    method: 'POST'
    body_format: json
    body: {
      "username": "{{ discord_name }}",
      "avatar_url": "{{ discord_avatar }}",
      "embeds": [
        {
        "title": "{{ discord_title }}",
        "description": "{{ discord_message }}",
        "color": "{{ discord_color }}"
        }
      ]
    }
    status_code: 204
  when:
    - discord_type == 'fancy'

#- name: Upload file to Discord
#  uri:
#    url: "{{ discord_webhook }}"
#    method: 'POST'
#    #body_format: json
#    headers:
#      Content-Type: multipart/form-data
#    body: {
#      "file1": files/ansible_logo.png
#    }

